"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-05-31

Baseline migration: provisions required extensions and creates the entire schema
(tables, enums, constraints, indexes) from the SQLAlchemy model metadata, which
is the single source of truth. Subsequent migrations are normal autogenerated
diffs against this baseline.
"""
from __future__ import annotations

from collections.abc import Sequence

from alembic import op

from app.models import Base

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    # CITEXT is required for case-insensitive admin emails.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    Base.metadata.create_all(bind=bind)


def downgrade() -> None:
    bind = op.get_bind()
    Base.metadata.drop_all(bind=bind)
